# Generated by Django 5.2.17 on 2026-09-26 23:51

import accounts.models
import django.db.models.functions.text
from django.db import migrations, models


def check_existing_emails(apps, schema_editor):
    """Stop before any schema change if existing rows cannot satisfy the new
    rules. Nothing is deleted or merged automatically: resolve the listed
    accounts by hand, then re-run migrate."""
    User = apps.get_model("accounts", "User")
    seen = {}
    empty, duplicates = [], []
    for pk, email in User.objects.order_by("pk").values_list("pk", "email"):
        normalized = (email or "").strip().lower()
        if not normalized:
            empty.append(pk)
        elif normalized in seen:
            duplicates.append((seen[normalized], pk))
        else:
            seen[normalized] = pk
    if empty or duplicates:
        raise RuntimeError(
            "Cannot switch to email login. "
            f"User ids with no email: {empty or 'none'}. "
            f"User id pairs sharing a normalized email: {duplicates or 'none'}."
        )


def normalize_existing_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        normalized = user.email.strip().lower()
        if normalized != user.email:
            user.email = normalized
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    # Reversal: the RunPython steps are no-ops backwards, but re-adding the
    # removed ``username`` column (NOT NULL, UNIQUE, no default) fails once any
    # account exists. Treat this migration as irreversible outside empty dev DBs.
    operations = [
        migrations.RunPython(check_existing_emails, migrations.RunPython.noop),
        migrations.RunPython(normalize_existing_emails, migrations.RunPython.noop),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", django.db.models.functions.text.Lower("email")),
                    models.Q(("email", ""), _negated=True),
                ),
                name="accounts_user_email_normalized",
                violation_error_message="Email must be non-empty and lowercase.",
            ),
        ),
    ]
