# Generated by Django 5.2.17 on 2026-09-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0002_composite_key_targets"),
        ("layouts", "0002_composite_key_targets"),
        ("markets", "0002_published_coords_index"),
        ("payments", "0001_initial"),
        ("reservations", "0002_payment_pending"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("payment_required", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="applications.application",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="markets.eventoccurrence",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="layouts.stalloffer",
                    ),
                ),
                (
                    "payment_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking",
                        to="payments.paymentattempt",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "vendor_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="vendors.vendorbusiness",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("payment_attempt__isnull", False),
                                ("payment_required", True),
                                ("price_minor__gt", 0),
                            ),
                            models.Q(
                                ("payment_attempt__isnull", True),
                                ("payment_required", False),
                                ("price_minor", 0),
                            ),
                            _connector="OR",
                        ),
                        name="bookings_payment_matches_price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_minor__gte", 0), ("price_minor__lte", 1000000000)
                        ),
                        name="bookings_price_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "currency__in",
                                (
                                    "USD",
                                    "CAD",
                                    "MXN",
                                    "EUR",
                                    "GBP",
                                    "AUD",
                                    "NZD",
                                    "JPY",
                                    "KRW",
                                ),
                            )
                        ),
                        name="bookings_currency_supported",
                    ),
                ],
            },
        ),
        # A booking's copies must match its reservation, and its payment
        # attempt must be for that same reservation.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE bookings_booking ADD CONSTRAINT bookings_matches_reservation "
                "FOREIGN KEY (reservation_id, offer_id, occurrence_id, application_id, "
                "vendor_business_id) REFERENCES reservations_reservation "
                "(id, offer_id, occurrence_id, application_id, vendor_business_id)",
                "ALTER TABLE bookings_booking ADD CONSTRAINT bookings_attempt_same_reservation "
                "FOREIGN KEY (payment_attempt_id, reservation_id) REFERENCES "
                "payments_paymentattempt (id, reservation_id)",
            ],
            reverse_sql=[
                "ALTER TABLE bookings_booking DROP CONSTRAINT bookings_attempt_same_reservation",
                "ALTER TABLE bookings_booking DROP CONSTRAINT bookings_matches_reservation",
            ],
        ),
    ]
