# Generated by Django 5.2.17 on 2026-09-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_composite_key_targets"),
        ("bookings", "0001_initial"),
        ("layouts", "0002_composite_key_targets"),
        ("markets", "0003_vendor_cancellation_cutoff"),
        ("payments", "0003_cancellation_refunds"),
        ("reservations", "0003_cancelled_and_policy_snapshot"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VENDOR", "Cancelled by the vendor"),
                            ("ORGANIZER", "Cancelled by the organizer"),
                            ("EVENT", "Date cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("requested_as", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True, max_length=1000)),
                ("internal_note", models.TextField(blank=True, max_length=1000)),
                ("requested_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("policy_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_vendor_cutoff_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "refund_rule",
                    models.CharField(
                        choices=[
                            ("PAID_MINUS_FEE", "Amount paid minus Vendi's fee"),
                            ("NO_PAYMENT", "Free booking: nothing to refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("refund_entitlement_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="OccurrenceCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_as", models.CharField(max_length=20)),
                ("requested_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OccurrenceCancellationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("HOLD", "Unpaid hold"),
                            ("CHECKOUT", "Hold with a checkout in progress"),
                            ("BOOKING", "Confirmed booking"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("DONE", "Done")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="policy_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="policy_vendor_cutoff_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("CONFIRMED", "Confirmed"), ("CANCELLED", "Cancelled")],
                default="CONFIRMED",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", True), ("status", "CONFIRMED")),
                    models.Q(("cancelled_at__isnull", False), ("status", "CANCELLED")),
                    _connector="OR",
                ),
                name="bookings_cancelled_at_matches",
            ),
        ),
        migrations.AddField(
            model_name="bookingcancellation",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancellation",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingcancellation",
            name="refund",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_cancellation",
                to="payments.refund",
            ),
        ),
        migrations.AddField(
            model_name="bookingcancellation",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="occurrencecancellation",
            name="occurrence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancellation_run",
                to="markets.eventoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="occurrencecancellation",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="occurrencecancellationitem",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="occurrencecancellationitem",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="bookings.occurrencecancellation",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingcancellation",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["VENDOR", "ORGANIZER", "EVENT"])),
                name="bookings_cancellation_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingcancellation",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_entitlement_minor__gte", 0)),
                name="bookings_cancellation_entitlement_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingcancellation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("refund_rule", "PAID_MINUS_FEE"),
                    ("refund_entitlement_minor", 0),
                    _connector="OR",
                ),
                name="bookings_cancellation_free_refunds_nothing",
            ),
        ),
        migrations.AddIndex(
            model_name="occurrencecancellationitem",
            index=models.Index(
                condition=models.Q(("status", "PENDING")),
                fields=["created_at"],
                name="bookings_cancel_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencecancellationitem",
            constraint=models.UniqueConstraint(
                fields=("run", "reservation"), name="bookings_cancellation_item_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencecancellationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("processed_at__isnull", True), ("status", "PENDING")),
                    models.Q(("processed_at__isnull", False), ("status", "DONE")),
                    _connector="OR",
                ),
                name="bookings_cancellation_item_processed_matches",
            ),
        ),
    ]
