# Generated by Django 5.2.17 on 2026-09-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_note", models.TextField(blank=True, max_length=1000)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restrictions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vendors.vendorbusiness",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "account"],
                        name="moderation_org_account_idx",
                    ),
                    models.Index(
                        fields=["organization", "vendor_business"],
                        name="moderation_org_vendor_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", False),
                                ("vendor_business__isnull", True),
                            ),
                            models.Q(
                                ("account__isnull", True),
                                ("vendor_business__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="moderation_restriction_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="moderation_restriction_reason_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="moderation_restriction_revocation_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__isnull", True),
                            ("expires_at__gt", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="moderation_restriction_expires_after_creation",
                    ),
                ],
            },
        ),
    ]
