# Generated by Django 5.2.17 on 2026-09-27 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("FARMERS_MARKET", "Farmers market"),
                            ("POPUP", "Popup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurrenceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval_weeks", models.PositiveSmallIntegerField()),
                (
                    "weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(), size=None
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("local_start_time", models.TimeField()),
                ("local_end_time", models.TimeField()),
                ("timezone", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "recurrence series",
            },
        ),
        migrations.CreateModel(
            name="EventOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=10,
                    ),
                ),
                ("cancellation_message", models.TextField(blank=True, max_length=500)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("series_slot_start", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="markets.market",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="markets.recurrenceseries",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="markets_market_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("market_type__in", ["FARMERS_MARKET", "POPUP"])),
                name="markets_market_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "ARCHIVED"])),
                name="markets_market_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(
                        ("latitude__gte", -90),
                        ("latitude__lte", 90),
                        ("longitude__gte", -180),
                        ("longitude__lte", 180),
                    ),
                    _connector="OR",
                ),
                name="markets_market_coordinates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country", ""), ("country__regex", "^[A-Z]{2}$"), _connector="OR"
                ),
                name="markets_market_country_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PUBLISHED"), _negated=True),
                    models.Q(
                        models.Q(("venue_name", ""), _negated=True),
                        models.Q(("address_line1", ""), _negated=True),
                        models.Q(("city", ""), _negated=True),
                        models.Q(("country", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="markets_market_published_has_venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrenceseries",
            constraint=models.UniqueConstraint(
                fields=(
                    "market",
                    "interval_weeks",
                    "weekdays",
                    "start_date",
                    "end_date",
                    "local_start_time",
                    "local_end_time",
                ),
                name="markets_series_unique_definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrenceseries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("interval_weeks__gte", 1), ("interval_weeks__lte", 12)
                ),
                name="markets_series_interval_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrenceseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="markets_series_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrenceseries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("local_end_time__gt", models.F("local_start_time"))
                ),
                name="markets_series_time_order",
            ),
        ),
        migrations.AddIndex(
            model_name="eventoccurrence",
            index=models.Index(
                fields=["market", "ends_at"], name="markets_occ_market_ends_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="markets_occurrence_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.UniqueConstraint(
                fields=("market", "starts_at"), name="markets_occurrence_unique_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.UniqueConstraint(
                fields=("series", "series_slot_start"),
                name="markets_occurrence_unique_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["SCHEDULED", "CANCELLED"])),
                name="markets_occurrence_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("series__isnull", True), ("series_slot_start__isnull", True)
                    ),
                    models.Q(
                        ("series__isnull", False), ("series_slot_start__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="markets_occurrence_series_slot_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", True), ("status", "SCHEDULED")),
                    models.Q(("cancelled_at__isnull", False), ("status", "CANCELLED")),
                    _connector="OR",
                ),
                name="markets_occurrence_cancelled_at_matches",
            ),
        ),
    ]
