# Generated by Django 5.2.17 on 2026-09-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                condition=models.Q(("status", "PUBLISHED")),
                fields=["latitude", "longitude"],
                name="markets_published_coords_idx",
            ),
        ),
    ]
