# Generated by Django 5.2.17 on 2026-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_published_coords_index"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="vendor_cancellation_cutoff_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("vendor_cancellation_cutoff_hours__lte", 8760)),
                name="markets_market_cancellation_cutoff_range",
            ),
        ),
    ]
