# Generated by Django 5.2.17 on 2026-09-27 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0002_composite_key_targets"),
        ("layouts", "0002_composite_key_targets"),
        ("markets", "0002_published_coords_index"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("EXPIRED", "Expired"),
                            ("RELEASED", "Released"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="HELD",
                        max_length=10,
                    ),
                ),
                ("price_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("expires_at", models.DateTimeField()),
                ("request_key", models.CharField(max_length=64)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="applications.application",
                    ),
                ),
                (
                    "held_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="markets.eventoccurrence",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="layouts.stalloffer",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="vendors.vendorbusiness",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="reservations_status_exp_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("HELD", "CONFIRMED"))),
                        fields=("offer",),
                        name="reservations_one_occupying_per_offer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("HELD", "CONFIRMED"))),
                        fields=("vendor_business", "occurrence"),
                        name="reservations_one_occupying_per_business_date",
                    ),
                    models.UniqueConstraint(
                        fields=("held_by", "vendor_business", "request_key"),
                        name="reservations_request_key_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["HELD", "EXPIRED", "RELEASED", "CONFIRMED"])
                        ),
                        name="reservations_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_minor__gte", 0), ("price_minor__lte", 1000000000)
                        ),
                        name="reservations_price_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "currency__in",
                                (
                                    "USD",
                                    "CAD",
                                    "MXN",
                                    "EUR",
                                    "GBP",
                                    "AUD",
                                    "NZD",
                                    "JPY",
                                    "KRW",
                                ),
                            )
                        ),
                        name="reservations_currency_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="reservations_expires_after_created",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_key", ""), _negated=True),
                        name="reservations_request_key_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(
                                    ("expired_at__isnull", False), ("status", "EXPIRED")
                                ),
                                models.Q(
                                    models.Q(("status", "EXPIRED"), _negated=True),
                                    ("expired_at__isnull", True),
                                ),
                                _connector="OR",
                            ),
                            models.Q(
                                models.Q(
                                    ("released_at__isnull", False),
                                    ("released_by__isnull", False),
                                    ("status", "RELEASED"),
                                ),
                                models.Q(
                                    models.Q(("status", "RELEASED"), _negated=True),
                                    ("released_at__isnull", True),
                                    ("released_by__isnull", True),
                                ),
                                _connector="OR",
                            ),
                            models.Q(
                                models.Q(
                                    ("confirmed_at__isnull", False),
                                    ("status", "CONFIRMED"),
                                ),
                                models.Q(
                                    models.Q(("status", "CONFIRMED"), _negated=True),
                                    ("confirmed_at__isnull", True),
                                ),
                                _connector="OR",
                            ),
                        ),
                        name="reservations_lifecycle_fields_match",
                    ),
                ],
            },
        ),
        # Composite foreign keys: PostgreSQL itself rejects a reservation whose
        # offer belongs to another date, or whose application belongs to
        # another date or vendor business. Targets are the composite unique
        # constraints added in layouts.0002 and applications.0002.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE reservations_reservation "
                "ADD CONSTRAINT reservations_offer_same_occurrence "
                "FOREIGN KEY (offer_id, occurrence_id) "
                "REFERENCES layouts_stalloffer (id, occurrence_id)",
                "ALTER TABLE reservations_reservation "
                "ADD CONSTRAINT reservations_application_same_occurrence_business "
                "FOREIGN KEY (application_id, occurrence_id, vendor_business_id) "
                "REFERENCES applications_application (id, occurrence_id, vendor_business_id)",
            ],
            reverse_sql=[
                "ALTER TABLE reservations_reservation "
                "DROP CONSTRAINT reservations_application_same_occurrence_business",
                "ALTER TABLE reservations_reservation "
                "DROP CONSTRAINT reservations_offer_same_occurrence",
            ],
        ),
    ]
