# Generated by Django 5.2.17 on 2026-09-27 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_composite_key_targets"),
        ("layouts", "0002_composite_key_targets"),
        ("markets", "0002_published_coords_index"),
        ("reservations", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="payment_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_pending", False), ("status", "HELD"), _connector="OR"
                ),
                name="reservations_payment_pending_only_held",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("id", "offer", "occurrence", "application", "vendor_business"),
                name="reservations_booking_key",
            ),
        ),
    ]
