# Generated by Django 5.2.17 on 2026-09-27 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_composite_key_targets"),
        ("layouts", "0002_composite_key_targets"),
        ("markets", "0003_vendor_cancellation_cutoff"),
        ("reservations", "0002_payment_pending"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="reservations_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reservation",
            name="reservations_lifecycle_fields_match",
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="policy_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="policy_vendor_cutoff_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held"),
                    ("EXPIRED", "Expired"),
                    ("RELEASED", "Released"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="HELD",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["HELD", "EXPIRED", "RELEASED", "CONFIRMED", "CANCELLED"],
                    )
                ),
                name="reservations_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("expired_at__isnull", False), ("status", "EXPIRED")),
                        models.Q(
                            models.Q(("status", "EXPIRED"), _negated=True),
                            ("expired_at__isnull", True),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(
                            ("released_at__isnull", False),
                            ("released_by__isnull", False),
                            ("status", "RELEASED"),
                        ),
                        models.Q(
                            models.Q(("status", "RELEASED"), _negated=True),
                            ("released_at__isnull", True),
                            ("released_by__isnull", True),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(
                            ("confirmed_at__isnull", False), ("status", "CONFIRMED")
                        ),
                        ("status", "CANCELLED"),
                        models.Q(
                            models.Q(
                                ("status__in", ["CONFIRMED", "CANCELLED"]),
                                _negated=True,
                            ),
                            ("confirmed_at__isnull", True),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        models.Q(
                            ("cancelled_at__isnull", False), ("status", "CANCELLED")
                        ),
                        models.Q(
                            models.Q(("status", "CANCELLED"), _negated=True),
                            ("cancelled_at__isnull", True),
                        ),
                        _connector="OR",
                    ),
                ),
                name="reservations_lifecycle_fields_match_v2",
            ),
        ),
    ]
