# Generated by Django 5.2.17 on 2026-09-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_published_coords_index"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=10,
                    ),
                ),
                ("questions_version", models.PositiveIntegerField()),
                ("questions", models.JSONField()),
                ("answers", models.JSONField()),
                ("vendor_snapshot", models.JSONField()),
                ("submitted_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_message", models.TextField(blank=True, max_length=2000)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="markets.eventoccurrence",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="vendors.vendorbusiness",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=10)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, max_length=5000)),
                ("questions", models.JSONField(default=list)),
                ("questions_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_intake",
                        to="markets.eventoccurrence",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["occurrence", "status"], name="applications_occ_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "vendor_business"),
                name="applications_one_per_business_occurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["SUBMITTED", "APPROVED", "REJECTED", "WITHDRAWN"])
                ),
                name="applications_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", False),
                        ("decided_by__isnull", False),
                        ("status__in", ("APPROVED", "REJECTED")),
                    ),
                    models.Q(
                        models.Q(
                            ("status__in", ("APPROVED", "REJECTED")), _negated=True
                        ),
                        ("decided_at__isnull", True),
                        ("decided_by__isnull", True),
                        ("decision_message", ""),
                    ),
                    _connector="OR",
                ),
                name="applications_decision_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "WITHDRAWN"),
                        ("withdrawn_at__isnull", False),
                        ("withdrawn_by__isnull", False),
                    ),
                    models.Q(
                        models.Q(("status", "WITHDRAWN"), _negated=True),
                        ("withdrawn_at__isnull", True),
                        ("withdrawn_by__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="applications_withdrawal_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "to_status__in",
                        ["SUBMITTED", "APPROVED", "REJECTED", "WITHDRAWN"],
                    )
                ),
                name="applications_event_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationintake",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_at__isnull", True),
                    ("closes_at__isnull", True),
                    ("closes_at__gt", models.F("opens_at")),
                    _connector="OR",
                ),
                name="applications_intake_window_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationintake",
            constraint=models.CheckConstraint(
                condition=models.Q(("questions_version__gte", 1)),
                name="applications_intake_version_positive",
            ),
        ),
    ]
