# Generated by Django 5.2.17 on 2026-09-27 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("markets", "0002_published_coords_index"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("id", "occurrence", "vendor_business"),
                name="applications_id_occurrence_business_unique",
            ),
        ),
    ]
