# Generated by Django 5.2.17 on 2026-09-27 16:36

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCE", "Produce"),
                            ("MEAT_DAIRY_EGGS", "Meat, dairy & eggs"),
                            ("BAKED_GOODS", "Baked goods"),
                            ("PREPARED_FOOD", "Prepared food"),
                            ("BEVERAGES", "Beverages"),
                            ("CRAFTS", "Crafts & art"),
                            ("FLOWERS_PLANTS", "Flowers & plants"),
                            ("HEALTH_BEAUTY", "Health & beauty"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("website", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "vendor businesses",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="vendors_business_name_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "category__in",
                                [
                                    "PRODUCE",
                                    "MEAT_DAIRY_EGGS",
                                    "BAKED_GOODS",
                                    "PREPARED_FOOD",
                                    "BEVERAGES",
                                    "CRAFTS",
                                    "FLOWERS_PLANTS",
                                    "HEALTH_BEAUTY",
                                    "OTHER",
                                ],
                            )
                        ),
                        name="vendors_business_category_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "contact_email",
                                django.db.models.functions.text.Lower("contact_email"),
                            ),
                            models.Q(("contact_email", ""), _negated=True),
                        ),
                        name="vendors_business_contact_email_normalized",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="vendors.vendorbusiness",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("business"),
                        models.F("email"),
                        condition=models.Q(("status", "PENDING")),
                        name="vendors_invitation_one_pending_per_email",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email", django.db.models.functions.text.Lower("email")),
                            models.Q(("email", ""), _negated=True),
                        ),
                        name="vendors_invitation_email_normalized",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["PENDING", "ACCEPTED", "REVOKED", "EXPIRED"],
                            )
                        ),
                        name="vendors_invitation_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "ACCEPTED"), _negated=True),
                            models.Q(
                                ("accepted_at__isnull", False),
                                ("accepted_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="vendors_invitation_accepted_has_acceptor",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("MEMBER", "Member")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="vendors.vendorbusiness",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "user"),
                        name="vendors_membership_one_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "OWNER")),
                        fields=("business",),
                        name="vendors_membership_one_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["OWNER", "MEMBER"])),
                        name="vendors_membership_role_valid",
                    ),
                ],
            },
        ),
    ]
