# Generated by Django 5.2.17 on 2026-09-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("reservations", "0002_payment_pending"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("livemode", models.BooleanField()),
                ("destination_account_id", models.CharField(max_length=64)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("application_fee_minor", models.BigIntegerField()),
                ("description", models.CharField(max_length=200)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("session_expires_at", models.DateTimeField()),
                (
                    "checkout_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATING", "Creating"),
                            ("OPEN", "Open"),
                            ("SUCCEEDED", "Succeeded"),
                            ("EXPIRED", "Expired"),
                            ("CANCELED", "Canceled"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATING",
                        max_length=10,
                    ),
                ),
                (
                    "fulfillment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULFILLED", "Fulfilled"),
                            ("UNFULFILLED", "Unfulfilled"),
                        ],
                        default="",
                        max_length=11,
                    ),
                ),
                ("provider_calls", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="vendors.vendorbusiness",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("UNFULFILLED", "Paid but not fulfilled")],
                        max_length=12,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("provider_calls", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=100)),
                ("livemode", models.BooleanField()),
                ("account", models.CharField(blank=True, default="", max_length=64)),
                ("object_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_created_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("processed_at__isnull", True)),
                        fields=["received_at"],
                        name="payments_event_unprocessed_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=64)),
                ("livemode", models.BooleanField()),
                ("charges_enabled", models.BooleanField(default=False)),
                ("application_fee_bps", models.PositiveIntegerField(default=100)),
                ("verified_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_account",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("livemode", "stripe_account_id"),
                        name="payments_account_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stripe_account_id__regex", "^acct_[A-Za-z0-9]+$")
                        ),
                        name="payments_account_id_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("application_fee_bps__lte", 10000)),
                        name="payments_account_fee_range",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["status", "fulfillment"], name="payments_attempt_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                fields=("id", "reservation"),
                name="payments_attempt_id_reservation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("CREATING", "OPEN", "SUCCEEDED"))),
                fields=("reservation",),
                name="payments_one_live_attempt_per_reservation",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checkout_session_id", ""), _negated=True),
                fields=("livemode", "checkout_session_id"),
                name="payments_attempt_session_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_intent_id", ""), _negated=True),
                fields=("livemode", "payment_intent_id"),
                name="payments_attempt_intent_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "CREATING",
                            "OPEN",
                            "SUCCEEDED",
                            "EXPIRED",
                            "CANCELED",
                            "FAILED",
                        ],
                    )
                ),
                name="payments_attempt_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_minor__gt", 0), ("amount_minor__lte", 1000000000)
                ),
                name="payments_attempt_amount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("application_fee_minor__gte", 0),
                    ("application_fee_minor__lte", models.F("amount_minor")),
                ),
                name="payments_attempt_fee_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "currency__in",
                        ("USD", "CAD", "MXN", "EUR", "GBP", "AUD", "NZD", "JPY", "KRW"),
                    )
                ),
                name="payments_attempt_currency_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("session_expires_at__gt", models.F("created_at"))),
                name="payments_attempt_expires_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["CREATING", "FAILED"]),
                    models.Q(("checkout_session_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="payments_attempt_session_when_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "SUCCEEDED"),
                        ("succeeded_at__isnull", False),
                        models.Q(("fulfillment", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "SUCCEEDED"), _negated=True),
                        ("fulfillment", ""),
                    ),
                    _connector="OR",
                ),
                name="payments_attempt_fulfillment_when_paid",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reason", "UNFULFILLED")),
                fields=("attempt",),
                name="payments_one_compensating_refund",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_refund_id", ""), _negated=True),
                fields=("stripe_refund_id",),
                name="payments_refund_stripe_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["REQUESTED", "PENDING", "SUCCEEDED", "FAILED", "CANCELED"],
                    )
                ),
                name="payments_refund_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gt", 0)),
                name="payments_refund_amount_positive",
            ),
        ),
    ]
