# Generated by Django 5.2.17 on 2026-09-27 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("payments", "0001_initial"),
        ("reservations", "0002_payment_pending"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentattempt",
            name="payments_attempt_amount_range",
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="fee_on_top",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_minor__gt", 0), ("amount_minor__lte", 2000000000)
                ),
                name="payments_attempt_amount_range",
            ),
        ),
    ]
