# Generated by Django 5.2.17 on 2026-09-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_fee_on_top"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="refund",
            name="payments_refund_status_valid",
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_application_fee",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.CharField(
                choices=[
                    ("UNFULFILLED", "Paid but not fulfilled"),
                    ("CANCELLATION", "Booking cancelled"),
                    ("EXTERNAL", "Refunded outside Vendi"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("PENDING", "Pending"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                    ("REVIEW", "Needs review"),
                ],
                default="REQUESTED",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reason", "CANCELLATION")),
                fields=("attempt",),
                name="payments_one_cancellation_refund",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason__in", ["UNFULFILLED", "CANCELLATION", "EXTERNAL"])
                ),
                name="payments_refund_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "REQUESTED",
                            "PENDING",
                            "SUCCEEDED",
                            "FAILED",
                            "CANCELED",
                            "REVIEW",
                        ],
                    )
                ),
                name="payments_refund_status_valid",
            ),
        ),
    ]
