# Generated by Django 5.2.17 on 2026-09-27 18:25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_published_coords_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StallLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_width", models.PositiveIntegerField()),
                ("canvas_height", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stall_layout",
                        to="markets.eventoccurrence",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("x", models.PositiveIntegerField()),
                ("y", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                (
                    "physical_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "physical_depth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "physical_unit",
                    models.CharField(
                        blank=True,
                        choices=[("FT", "feet"), ("M", "meters")],
                        max_length=2,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("price_minor", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stalls",
                        to="layouts.stalllayout",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="stalllayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("canvas_width__gte", 1),
                    ("canvas_width__lte", 10000),
                    ("canvas_height__gte", 1),
                    ("canvas_height__lte", 10000),
                ),
                name="layouts_layout_canvas_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="stalllayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "currency__in",
                        ("USD", "CAD", "MXN", "EUR", "GBP", "AUD", "NZD", "JPY", "KRW"),
                    )
                ),
                name="layouts_layout_currency_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="stalllayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="layouts_layout_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.UniqueConstraint(
                models.F("layout"),
                django.db.models.functions.text.Lower("label"),
                name="layouts_stall_label_unique_in_layout",
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="layouts_stall_label_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gte", 1), ("width__gte", 1)),
                name="layouts_stall_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_minor__gte", 0), ("price_minor__lte", 1000000000)
                ),
                name="layouts_stall_price_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="stall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("physical_depth__isnull", True),
                        ("physical_unit", ""),
                        ("physical_width__isnull", True),
                    ),
                    models.Q(
                        ("physical_depth__gt", 0),
                        ("physical_unit__in", ["FT", "M"]),
                        ("physical_width__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="layouts_stall_physical_size_complete",
            ),
        ),
    ]
