# Generated by Django 5.2.17 on 2026-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layouts", "0001_initial"),
        ("markets", "0002_published_coords_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stalloffer",
            constraint=models.UniqueConstraint(
                fields=("id", "occurrence"), name="layouts_offer_id_occurrence_unique"
            ),
        ),
    ]
